/*******************************************************************************
Code generated by cplatkm 
*******************************************************************************/

const createCrudApi = require('./GenericCrudApi');

const Batches = require('../model/Batches'); 
const Clients = require('../model/Clients'); 

function registerCrudRoutes(app) {
	app.use('/api/batches', createCrudApi(Batches)); 
	app.use('/api/clients', createCrudApi(Clients)); 

}

module.exports = registerCrudRoutes;