/*******************************************************************************
Code generated by cplatkm 
*******************************************************************************/

const createCrudApi = require('./GenericCrudApi');

const Valtab = require('../model/Valtab'); 
const Clients = require('../model/Clients'); 
const BatchEntries = require('../model/BatchEntries'); 
const Categories = require('../model/Categories'); 
const BatchMovements = require('../model/BatchMovements'); 
const Products = require('../model/Products'); 

function registerCrudRoutes(app) {
	app.use('/api/valtab', createCrudApi(Valtab)); 
	app.use('/api/clients', createCrudApi(Clients)); 
	app.use('/api/batchentries', createCrudApi(BatchEntries)); 
	app.use('/api/categories', createCrudApi(Categories)); 
	app.use('/api/batchmovements', createCrudApi(BatchMovements)); 
	app.use('/api/products', createCrudApi(Products)); 

}

module.exports = registerCrudRoutes;