 /*******************************************************************************
Code generated by cplatkm 
*******************************************************************************/

class Batches {
  
  static tableName = 'batches';

  static schema = {
		batch_id:{type:'number', primary: true}
		,product_id:{type:'number'}
		,batch_number:{type:'string'}
		,manufacture_date:{type:'Date'}
		,expiry_date:{type:'Date'}
		,initial_quantity:{type:'number'}
		,available_quantity:{type:'number'}
		,status:{type:'boolean'}
  };

 	constructor({batch_id,product_id,batch_number,manufacture_date,expiry_date,initial_quantity,available_quantity,status}) {
		this.batch_id = batch_id;
		this.product_id = product_id;
		this.batch_number = batch_number;
		this.manufacture_date = manufacture_date;
		this.expiry_date = expiry_date;
		this.initial_quantity = initial_quantity;
		this.available_quantity = available_quantity;
		this.status = status;
  }
}

module.exports = Batches;